"""Jeli's own stickers, for the feelings the groups have no sticker of their own for yet.

Jeli answers a strong feeling with one of the groups' stickers: their visual language, learned as
members use it. Measured on 23 September, it had learned none — the feature was built and its
cupboard was empty, so it could never say anything.

These are what it uses meanwhile. Each one is the very emoji Jeli already puts on a message for
that feeling, drawn large (scripts/make_stickers.py): nothing invented, nothing generated by a
model, nothing that can run out of quota. The group's own sticker still comes first the moment
Jeli has one.
"""

import logging
from pathlib import Path

log = logging.getLogger(__name__)

HERE = Path(__file__).resolve().parent.parent.parent / "assets" / "stickers"
MIMETYPE = "image/webp"


def _name(emoji: str) -> str:
    """"😂" -> "1f602": the code points, without the variation and joining marks."""
    return "-".join(f"{ord(ch):x}" for ch in emoji if ord(ch) not in (0xFE0F, 0x200D))


def for_reaction(emoji: str) -> bytes | None:
    """The sticker that says the same thing as this reaction, or None when there is none."""
    if not emoji:
        return None
    path = HERE / f"{_name(emoji)}.webp"
    try:
        return path.read_bytes() if path.is_file() else None
    except OSError:
        log.warning("Could not read the sticker %s", path, exc_info=True)
        return None


def known() -> list[str]:
    """The sticker files Jeli ships with — for the dashboard and the tests."""
    return sorted(path.stem for path in HERE.glob("*.webp")) if HERE.is_dir() else []
