"""Jeli's own sticker pack, drawn once from the emojis it already reacts with.

    python -m scripts.make_stickers

Jeli answers a strong feeling with one of the groups' own stickers — their visual language, not a
pack of its own. But measured on 23 September, it had learned none: members had sent it none since
the feature shipped, so the cupboard was empty and it could never say anything. These are what it
uses meanwhile, and what it falls back on for a feeling the groups have no sticker for.

They are not invented images: each one is the emoji Jeli already puts on a message for that
feeling (app/answer/emotion.py), drawn large. Nothing is generated by a model, so nothing depends
on a quota, and what the sticker says is exactly what the reaction says.
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, ".")
from app.answer.emotion import REACTIONS  # noqa: E402

# WhatsApp stickers are 512×512 with a transparent background.
SIZE = 512
MARGIN = 24
# Fonts that carry the colour emoji glyphs, in the order they are looked for.
FONTS = [
    "C:/Windows/Fonts/seguiemj.ttf",
    "/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf",
    "/System/Library/Fonts/Apple Color Emoji.ttc",
]
# Segoe UI Emoji draws its colour bitmaps at this size; asking for more gives an outline.
DRAW_SIZE = 109
HERE = Path("assets/stickers")


def font() -> ImageFont.FreeTypeFont:
    for path in FONTS:
        if Path(path).exists():
            return ImageFont.truetype(path, DRAW_SIZE)
    raise SystemExit("No colour emoji font found: run this where one is installed (Windows, or Noto on Linux).")


def name_of(emoji: str) -> str:
    """A file name from the emoji's code points: "😂" -> "1f602"."""
    return "-".join(f"{ord(ch):x}" for ch in emoji if ord(ch) not in (0xFE0F, 0x200D))


def draw(emoji: str, glyphs: ImageFont.FreeTypeFont) -> Image.Image:
    small = Image.new("RGBA", (DRAW_SIZE * 2, DRAW_SIZE * 2), (0, 0, 0, 0))
    ImageDraw.Draw(small).text(
        (DRAW_SIZE, DRAW_SIZE), emoji, font=glyphs, anchor="mm", embedded_color=True
    )
    box = small.getbbox()
    if box:
        small = small.crop(box)
    side = SIZE - 2 * MARGIN
    scale = min(side / small.width, side / small.height)
    small = small.resize((max(1, int(small.width * scale)), max(1, int(small.height * scale))), Image.LANCZOS)
    sticker = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    sticker.paste(small, ((SIZE - small.width) // 2, (SIZE - small.height) // 2), small)
    return sticker


def main() -> None:
    glyphs = font()
    HERE.mkdir(parents=True, exist_ok=True)
    made = 0
    for emoji in REACTIONS:
        sticker = draw(emoji, glyphs)
        if not sticker.getbbox():
            print(f"  {name_of(emoji)} drew nothing - skipped")
            continue
        path = HERE / f"{name_of(emoji)}.webp"
        sticker.save(path, "WEBP", lossless=True)
        made += 1
        print(f"  {path}  {path.stat().st_size:,} bytes")
    print(f"{made} stickers in {HERE}")


main()
