"""Jeli's own sticker pack, drawn and animated once from the emojis it already reacts with.

    python -m scripts.make_stickers

Jeli answers a strong feeling with one of the groups' own stickers — their visual language, not a
pack of its own. But measured on 23 September it had learned none: members had sent it none since
the feature shipped, so the cupboard was empty and it could never say anything. These are what it
uses meanwhile, and what it falls back on for a feeling the groups have no sticker for.

They are not borrowed and not invented: each one is the emoji Jeli already puts on a message for
that feeling (app/answer/emotion.py), drawn large and given a little motion. Nothing comes from a
catalogue of someone else's images, so nothing can arrive off-tone in a 240-person group; nothing
is generated by a model, so nothing depends on a quota; and what the sticker says is exactly what
the reaction says.
"""

import io
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, ".")
from app.answer.stickers import FOR_FEELING  # noqa: E402

# WhatsApp stickers are 512×512 with a transparent background, and animated ones must stay under
# 500 KB — measured: 12 frames of a 440 px emoji come to about 165 KB.
SIZE = 512
DRAWN = 440
MAX_BYTES = 500_000
FRAMES = 12
FRAME_MS = 70
# Fonts that carry the colour emoji glyphs, in the order they are looked for.
FONTS = [
    "C:/Windows/Fonts/seguiemj.ttf",
    "/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf",
    "/System/Library/Fonts/Apple Color Emoji.ttc",
]
# Segoe UI Emoji draws its colour bitmaps at this size; asking for more gives a flat outline.
DRAW_SIZE = 109
HERE = Path("assets/stickers")

# How each one moves. A sticker that bounces like a cheer and one that breathes like a thank-you
# are not the same message, and the motion is the last thing that tells them apart.
BOUNCE = "bounce"    # celebrations: a jump with a little squash
PULSE = "pulse"      # warmth: a heartbeat
SHAKE = "shake"      # laughter: a quick tilt left and right
BREATHE = "breathe"  # gravity: a slow swell, nothing sudden
# One motion per feeling, not per emoji: a new sticker added to a family moves like its family,
# and nobody has to remember to describe it twice.
MOTION = {
    "joy": BOUNCE, "pride": BOUNCE, "encouragement": BOUNCE,
    "love": PULSE, "gratitude": PULSE,
    "humor": SHAKE,
    "sadness": BREATHE,
}


def font() -> ImageFont.FreeTypeFont:
    for path in FONTS:
        if Path(path).exists():
            return ImageFont.truetype(path, DRAW_SIZE)
    raise SystemExit("No colour emoji font found: run this where one is installed (Windows, or Noto on Linux).")


def name_of(emoji: str) -> str:
    """A file name from the emoji's code points: "😂" -> "1f602"."""
    return "-".join(f"{ord(ch):x}" for ch in emoji if ord(ch) not in (0xFE0F, 0x200D))


def glyph(emoji: str, glyphs: ImageFont.FreeTypeFont) -> Image.Image:
    """The emoji alone, cropped to its ink and scaled to the drawing size."""
    canvas = Image.new("RGBA", (DRAW_SIZE * 2, DRAW_SIZE * 2), (0, 0, 0, 0))
    ImageDraw.Draw(canvas).text((DRAW_SIZE, DRAW_SIZE), emoji, font=glyphs, anchor="mm", embedded_color=True)
    box = canvas.getbbox()
    if not box:
        return canvas
    ink = canvas.crop(box)
    scale = min(DRAWN / ink.width, DRAWN / ink.height)
    return ink.resize((max(1, int(ink.width * scale)), max(1, int(ink.height * scale))), Image.LANCZOS)


def placed(ink: Image.Image, scale: float, lift: int, tilt: float) -> Image.Image:
    frame = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    moved = ink
    if tilt:
        moved = moved.rotate(tilt, resample=Image.BICUBIC, expand=True)
    if scale != 1.0:
        moved = moved.resize((max(1, int(moved.width * scale)), max(1, int(moved.height * scale))), Image.LANCZOS)
    frame.paste(moved, ((SIZE - moved.width) // 2, (SIZE - moved.height) // 2 - lift), moved)
    return frame


def animate(ink: Image.Image, motion: str) -> list[Image.Image]:
    frames = []
    for step in range(FRAMES):
        turn = step / FRAMES * 2 * math.pi
        if motion == BOUNCE:
            height = max(0.0, math.sin(turn))
            frames.append(placed(ink, 1 - 0.08 * height, int(34 * height), 0))
        elif motion == PULSE:
            beat = math.sin(turn) ** 2
            frames.append(placed(ink, 1 + 0.09 * beat, 0, 0))
        elif motion == SHAKE:
            frames.append(placed(ink, 1.0, int(8 * abs(math.sin(turn))), 7 * math.sin(turn)))
        else:  # BREATHE
            frames.append(placed(ink, 1 + 0.045 * math.sin(turn), int(6 * math.sin(turn)), 0))
    return frames


def encode(frames: list[Image.Image]) -> bytes:
    """The animation as WebP, quality lowered only as far as the 500 KB limit demands."""
    for quality in (80, 70, 60, 50, 40):
        buffer = io.BytesIO()
        frames[0].save(
            buffer, "WEBP", save_all=True, append_images=frames[1:], duration=FRAME_MS,
            loop=0, lossless=False, quality=quality, method=4,
        )
        data = buffer.getvalue()
        if len(data) <= MAX_BYTES:
            return data
    return data


def main() -> None:
    glyphs = font()
    HERE.mkdir(parents=True, exist_ok=True)
    made = 0
    for feeling, emojis in FOR_FEELING.items():
        for emoji in emojis:
            ink = glyph(emoji, glyphs)
            if not ink.getbbox():
                print(f"  {name_of(emoji)} ({feeling}) drew nothing - skipped")
                continue
            moves = MOTION.get(feeling, BREATHE)
            data = encode(animate(ink, moves))
            path = HERE / f"{name_of(emoji)}.webp"
            path.write_bytes(data)
            made += 1
            print(f"  {path}  {len(data):,} bytes  {feeling}/{moves}")
    print(f"{made} animated stickers in {HERE}")


main()
